##################################################
# Regex pattern for identifying non-person names #
# Jacob Goldstein-Greenwood                      #
# GitHub: jacob-gg                               #
# Last revised: 2022-10-31                       #
##################################################

non_person_regex <- paste0('(?i)',
                           paste0(c('(\\bac(adem(y|ics?)|oustics?)\\b)',
                                    '(\\bad(ministrations?|v(entures?|is(ers?|ors?|ing)))\\b)',
                                    '(\\ba(ff(airs?|ordable)|genc(y|ies)|ir(line|port)s?)\\b)',
                                    '(\\bal(l|terations?|um(nus|na|ni|nae)?)\\b)',
                                    '(\\ba(merican?|n(alys((e|i)s|ts?)|d|tiques?)|p(artments?|parel|prais(als?|ers?|ing)|pliances?))\\b)',
                                    '(\\bass(oc(iat(es?|ions?))?|n)\\.?\\b)',
                                    '(\\ba(rchitect(ur(al|e)|s)?|rchiv(al|es?)|ttorneys?|(quarium|sylum)s?|viation)\\b)',
                                    '(\\bau(to(motive)?s?|diology)\\b)',
                                    '(\\bbak(ers?|ery|ing)\\b)',
                                    '(\\bba(nk(ing)?|ptist|r(n|be(cu(e|ing)|r(s|shops?)?))|ths?)\\b)',
                                    '(\\bb(bq|e(auty|d|er)|i(ble|stros?)|o(nds|utiques?))\\b)',
                                    '(\\bbook(s(tore|hop|ellers?)?)?\\b)',
                                    '(\\bbr(aids?|o(ker|w)s?|e(akfast|wer(y|ies)))\\b)',
                                    '(\\bbu(dgets?|ild(ings?|ers?)|reaus?|siness(es)?|tchers?|y)\\b)',
                                    '(\\bca(binet|rpenter)(s|ry)\\b)',
                                    '(\\bc\\/?o\\.?\\b)',
                                    '(\\bca(rs?|fes?|noe(s|ing)?|pital|tholic|ter(ing|ers?))\\b)',
                                    '(\\bc(e(llular|meter(ies|y)|nt(er|re)s?)|i?(nemas?|ty))\\b)',
                                    '(\\bcl(ean(ers?|ing)|imbing?|inics?|oth(es|ing))\\b)',
                                    '(\\bco(astal|ffee|ll(aborative|ege|ision)s?|mm(erc(e|ials?)|(issi)?ons?|uni(cations?|t(y|ies)))|mp(an(ies|y)|uters?)|smetics?|un(cil|ty))\\b)',
                                    '(\\bcon(crete|d(itioning|o(minium)?s?)|s(ignment|truction|ult(ing|ants?)?)|tract(ing|ors?))\\b)',
                                    '(\\bc(o(\\-|\\s)?op(eratives?)?|\\.?p\\.?)\\b)',
                                    '(\\bcorp(oration|\\.)?\\b)',
                                    '(\\bcorrection(al|s)\\b)',
                                    '(\\bc(harters?|o(oling|p(ies|ying)|uriers?)|r(edit|ossings?|uise(line)?s?))\\b)',
                                    '(\\bcu(t(s|z)?|sto(dia(l|n)|m)s?|isine)\\b)',
                                    '(\\bda(ta|y(\\s{1})?care)\\b)',
                                    '(\\bd(\\/\\.)?b(\\/\\.)?a\\.?\\b)',
                                    '(\\bde(corat(ing|ors?)|partments?|tail(ers?|ing))\\b)',
                                    '(\\bde(nt(al|ist(s|ry)?)|sign(ers?|ing|s)?|lis?|velop(er|ment)s?)\\b)',
                                    '(\\bd(i(a(gnostics?|lysis)|gital|ocese|scounts?|sposal|vision)|octors?|uplex(es)?)\\b)',
                                    '(\\be(ater(y|ies)|states?|x(c(avat(ions?|ing|ors?)|ursions?)|terminat(ors?|ing)))\\b)',
                                    '(\\be(lectr(ic(al|ians?)|onics?)?|n(ter(prises?|tainment)|vironmental|gineer(s|ing)?)|qui(pment|t(ies|y))|ye)\\b)',
                                    '(\\bfa(ctor(y|ies)|mil(ies|y)|rm(ing|s)?)\\b)',
                                    '(\\bf(i(nanc(es?|i(al|ng))|r(m|earms?)|shing)|e(dera(l|tions?)|llowships?))\\b)',
                                    '(\\bf(lor(al|ists?)|loor(ing|s)?|oundation|u(n(ding|erals?)|rni(shings?|ture))|reight)\\b)',
                                    '(\\bg(a(ller(ies|y)|rdens?)|ifts?|lobal|r(ill(s|ing)?|oups?|ocer(ies|s|y)?)|un(s(miths?)?)?)\\b)',
                                    '(\\bha(ir(cut(s|ters?)?)?|ndym(a|e)n|rdware|tcher(ies|y))\\b)',
                                    '(\\bhea(lth(care)?|ting)\\b)',
                                    '(\\bh(eights?|istorical|o(ldings?|me(\\-?builder)?s?|tels?|us(ing|es?))|umans?|v\\-?ac)\\b)',
                                    '(\\binc(\\.|orporated)?\\b)',
                                    '(\\bin(dustr(i(al|es)|y)|n|s(pecti(ng|ons?)|urance|t(allers?|itut(e|ion(s|al)?)))|ter(n(ational|et)|iors?)|vest(ing|ments?|ors?))\\b)',
                                    '(\\bi(sla(mic|nds?)|t)\\b)',
                                    '(\\bje(rusalem|w(el(ry|s|ers?)|ish))\\b)',
                                    '(\\bj(a(il(ers?)?|nitor(ial|s)?)|unk)\\b)',
                                    '(\\bk(ayak(ing|s)?|itchen(s|ry)?)\\b)',
                                    '(\\bla(bor(ers?)?|ndscap(e(rs?)?|ing)|undr(omat|y)|wn)\\b)',
                                    '(\\bli(brar(ies|y)|fe|m(ited|o(usine)?s?)|quors?)\\b)',
                                    '(\\b((p|r)\\.?)?l\\.?((l\\.?)?(c|s)|td|(l\\.?){0,2}?p)\\.?\\b)',
                                    '(\\bl(ega(c(ies|y)|l)|o(an(s|z)?|dg(e|ing)s?|fts?|tter(ies|y)|unges?)|u(mber|theran|xur(ies|y)))\\b)',
                                    '(\\bm(alls?|hp)\\b)',
                                    '(\\bm(ana)?g(e)?m(en)?t\\.?\\b)',
                                    '(\\bmanufactur(ers?|ing)\\b)',
                                    '(\\bma(nors?|ssage|rkets?)\\b)',
                                    '(\\bme(chanics?|dical|t(hodist|ro(politan)?))\\b)',
                                    '(\\bminist(ers?|ry|ries)\\b)',
                                    '(\\bmo(biles?|rtgages?|sque|t(els?|ors?)|ving)\\b)',
                                    '(\\bmu(fflers?|ltiplex(es)?|nicipal(ity)?|sic(ians?)?)\\b)',
                                    '(\\bnat((iona)?l|ions?)\\b)',
                                    '(\\bnetwork(s|ing)?\\b)',
                                    '(\\bno(n(\\-|\\s)?profit|odles?)\\b)',
                                    '(\\bnurs(er(ies|y)|ing)\\b)',
                                    '(\\boil\\b)',
                                    '(\\boffices?\\b)',
                                    '(\\boptic(al|ians?)\\b)',
                                    '(\\borganizations?\\b)',
                                    '(\\borthodonti(sts?|cs)\\b)',
                                    '(\\bo(utfitter|wner)s?\\b)',
                                    '(\\bpa(int(ers|ings?)?|yday)\\b)',
                                    '(\\b(p\\.?a\\.?|p\\.?b?\\.?c\\.?)\\b)',
                                    '(\\bpe(ntecostal|sts?)\\b)',
                                    '(\\bpet(roleum|s|smart)?\\b)',
                                    '(\\bp(h(armaceuticals?|otograph(ers?|y))|izzas?)\\b)',
                                    '(\\bp(ar(king|tner(ship)?s?)|l(ace|azas?|c|umb(ers?|ing))|ortfolios?|ub)\\b)',
                                    '(\\bpr(e(mier|sbyterian|\\-?schools?)|i(nt(ing|ers?)|sons?)|o(ductions?|grams?|pert(ies|y)))\\b)',
                                    '(\\bpublic(i(sts?|ty))?\\b)',
                                    '(\\breal(t(y|ors?)|(\\-|\\s{1})estate)\\b)',
                                    '(\\bre(cord(ing|s)?|gional|model(s?|ers?|ing)?|n(ovat(i(ng|ons?)|ors?)|tals?)|pairs?|s(idence|o(rts?|urce)|taurant)s?|tail(ers?)?)\\b)',
                                    '(\\bs(ailing|al(oo?n|ad)s?|c(ientific|hools?)|e(afood|curity|ptic|rvices?|wing)|ight\\-?seeing|kin)\\b)',
                                    '(\\bsh(o(es?|wrooms?|p(s|pes?)?)|ipp(ers?|ing))\\b)',
                                    '(\\bso(ciet(ies|y)|ft\\-?ware|lutions?)\\b)',
                                    '(\\bsp(a|ecialists?|ort(s|ing|\\-?fishing)?)\\b)',
                                    '(\\bst(a(ff(ing|ers?)?|te|tions?)|orage|udios?|reets?)\\b)',
                                    '(\\bsu(ccessors?|ites?|shi|ppl(ies|y)|r(g(e(ons?|ry)|ical)|plus)|per(\\-?stores?|vis(ing|ors?)))\\b)',
                                    '(\\bsy(stems?|nagogue)\\b)',
                                    '(\\bta(bernacle|nning|xis?|x(es)?)\\b)',
                                    '(\\bthe(at(er|re)|rap(eutics?|ists?|y))?\\b)',
                                    '(\\bt(ermites?|(i|y)res?|o(ur(ing|s)?|ys?|w(ers?|ing)|wn\\-?ho(m|us)es?))\\b)',
                                    '(\\btr(a((d|in)ing|nsportation)|u(ck(ers?|ing)|st(ee)?s?))\\b)',
                                    '(\\bu(n(i(versity|ted)|limited)|rban|tilit(ies|y))\\b)',
                                    '(\\bv(e(hicle|nture|teran)s?|i(deo|llage|neyard)s?)\\b)',
                                    '(\\bwa(rehous(es?|ing)|shing)\\b)',
                                    '(\\bw((elln|irel)ess|i\\-?fi|ine(ry|ies)?|orld)\\b)',
                                    '(\\bwreck(ing|ers?)\\b)',
                                    '(\\by(mca|outh)\\b)',
                                    '(\\b(up|down|mid)\\-?town\\b)',
                                    '(\\d+)|(\\&)|(\\@)|(\\!)|(\\#)|(\\%)|(\\/)', # non-person characters
                                    "(\\'s\\s{1,}|\\'s$|s\\'\\s{1,}|s\\'$)", # possessives
                                    '(https?\\:\\/\\/)|(www\\.)|(\\.(biz|com|edu|gov|int|mil|net|org))', # websites
                                    '(\\ba((a|t)|by|for|in|o(n|ut)|off?|too?)\\b)', # common prepositions
                                    '(\\b(b(ou)?le?v(ar)?d|c(our)?t|la?ne?|r(oa)?d|st(reet)?)\\b)', # common street indicators
                                    '(\\b((north|east|south|west)(ern)?|north\\-?(east|west)|south\\-?(east|west))\\b)'), # cardinal directions
                                  collapse = '|')
)

