##################################################
# Regex pattern for identifying non-person names #
# Jacob Goldstein-Greenwood                      #
# GitHub: jacob-gg                               #
# Last revised: 2023-10-30                       #
##################################################

non_person_regex <- paste0('(?i)',
                           paste0(c('(\\bac(adem(y|ics?)|oustics?|res?|quisitions?)\\b)',
                                    '(\\bad(ministrations?|v(ent(ist|ures?)|is((e|o)rs?|ing)))\\b)',
                                    '(\\ba(ff(airs?|ordable)|gen(ts?|c(y|ies))|ir(line|port)s?)\\b)',
                                    '(\\bal(l(iances?)?|terations?|um(nus|na|ni|nae)?)\\b)',
                                    '(\\ba(merican?|n(alys((e|i)s|ts?)|d|tiques?)|p(artments?|parel|prais(als?|ers?|ing)|pliances?))\\b)',
                                    '(\\bass(istive|oc(iat(es?|ions?))?|n)\\.?\\b)',
                                    '(\\ba(rchitect(ur(al|e)|s)?|rchiv(al|es?)|t(lantic|torneys?)|(qua(rium|tic)|sylum)s?|viation)\\b)',
                                    '(\\bau(to(body|motives?)?|diology)\\b)',
                                    '(\\bba(il|nk(ers?|ing)?|k(er(s|y)|ing)|ptist|r(n|be(cu(e|ing)|r(s|shops?)))|ths?)\\b)',
                                    '(\\bb(bq|e(auty|d|er)|i(ble|stros?)|outiques?)\\b)',
                                    '(\\bbook(s(tore|hop|ellers?)?)?\\b)',
                                    '(\\bbr(aids?|o(adcast(ers?|ing)?|(ker|w)s?)|e(akfast|wer(y|ies)))\\b)',
                                    '(\\bbu(dgets?|ild(ings?|ers?)|reaus?|siness(es)?|tchers|y)\\b)',
                                    '(\\bc\\/?o\\.?\\b)',
                                    '(\\bca(binet|rpenter)(s|ry)\\b)',
                                    '(\\bca(re|rs?|fes?|noe(s|ing)?|pital|tholic|ter(ing|ers?))\\b)',
                                    '(\\bc(e(llular|meter(ies|y)|nt(er|re)s?)|i?(nemas?|ty))\\b)',
                                    '(\\bcl(ean(ers?|ing)|imbing?|inics?|oth(es|ing)|ubs?)\\b)',
                                    '(\\bco(astal|ffee|ll(aborative|e(ctions?|ge)|ision)s?|lonial|mm(erc(e|ials?)|(issi)?ons?|uni(cations?|t(y|ies)))|mp(an(ies|y)|uters?)|s(metic|t(ume)?)s?|un(cils|t(ies|y)))\\b)',
                                    '(\\bcon(crete|d(itioning|o(minium)?s?)|s(ignment|truction|ult(ing|ants?)?)|tract(ing|ors?))\\b)',
                                    '(\\bc(o(\\-|\\s)?op(eratives?)?|\\.?p\\.?)\\b)',
                                    '(\\bcorp(orat(e|ion)|\\.)?\\b)',
                                    '(\\bc(h(a(pel|rter)s?|ild(\\-?care|ren)|urches)|o(oling|p(ies|ying)|r(o?ners?|rection(al|s))|ttages?|ves?|u(ntr(ies|y)|riers?|nsel(ers?|ing)))|r(e(ative|dit|st)s?|ossings?|uise(line)?s?))\\b)',
                                    '(\\bcu(t(s|z)?|sto(dia(l|n)|m)s?|isine)\\b)',
                                    '(\\bda(ta|y(\\s{1}|\\-)?care)\\b)',
                                    '(\\bd(\\/|\\.)?b(\\/|\\.)?a\\.?\\b)',
                                    '(\\bde(bts?|corat(ing|ors?)|partments?|tail(ers?|ing))\\b)',
                                    '(\\bde(nt(al|ist(s|ry)?)|sign(ers?|ing|s)?|lis?|velop(er|ment)s?)\\b)',
                                    '(\\bd(i(a(gnostics?|lysis)|gital|ning|ocese|s(counts?|posal|tricts?)|vision)|o(cto|lla)rs?|uplex(es)?)\\b)',
                                    '(\\be(ater(y|ies)|states?|x(c(avat(ions?|ing|ors?)|ursions?)|press|terminat(ors?|ing)))\\b)',
                                    '(\\be(lectr(ic(al|ians?)?|onics?)|n(ter(prises?|tainment)|vironmental|gineer(s|ing)?)|qui(pment|t(ies|y))|ye)\\b)',
                                    '(\\bfa(bricati(ng|on)|ctor(y|ies)|mil(ies|y)|rm(ing|s)?)\\b)',
                                    '(\\bf(e(dera(l|tions?)|es?|llowships?)|i(nanc(es?|i(al|ng))|r(e(arm)?s?|ms?|st)|shing))\\b)',
                                    '(\\bf(lor(al|ists?)|loor(ing|s)?|oundations?|u(n(d(ing|s)?|erals?)|rni(shings?|ture))|reight)\\b)',
                                    '(\\bg(a(ller(ies|y)|m(es?|ing)|rdens?)|enerators?|ifts?|lobal|ospel|r(ill(s|ing)?|o(ups?|cer(ies|s|y)?))|un(s(miths?)?)?)\\b)',
                                    '(\\bha(bitats?|ir(cut(s|ters?)?)?|ndym(a|e)n|rdware|tcher(ies|y))\\b)',
                                    '(\\bhea(lth(care)?|ting)\\b)',
                                    '(\\bh(eights|istoric(al)?|o(l(dings?|iness)|me(\\-?bu(ild|y)er)?s?|spital(s|ity)?|tels?|us(ing|es))|uman(ity|s)?|v\\-?ac)\\b)',
                                    '(\\binc(\\.|orporated)?\\b)',
                                    '(\\bin(dustr(i(al|es)|y)|n|s(pecti(ng|ons?)|urance|t(allers?|itut(e|ion(s|al)?)))|ter(n(ational|et)|iors?)|vest(ing|ments?|ors?))\\b)',
                                    '(\\bi(sla(mic|nds?)|t)\\b)',
                                    '(\\bje(rusalem|w(el(ry|s|ers?)|ish))\\b)',
                                    '(\\bj(a(il(ers?)?|nitor(ial|s)?)|unk)\\b)',
                                    '(\\bk(ayak(ing|s)?|itchen(s|ry)?)\\b)',
                                    '(\\bla(bor(ers?)?|ndscap(e(rs?)?|ing)|undr(omat|y)|wn)\\b)',
                                    '(\\bli(brar(ies|y)|fe|m(ited|ousines?)|quors?|ving)\\b)',
                                    '(\\b((p|r)\\.?)?l\\.?((l\\.?)?c|td|(l\\.?){0,2}?p)\\.?\\b)',
                                    '(\\bl(e(asing|ga(c(ies|y)|l))|o(an(s|z)?|dg(e|ing)s?|fts?|tter(ies|y)|unges?)|u(mber|theran|xur(ies|y)))\\b)',
                                    '(\\bm(alls?|h(c|p))\\b)',
                                    '(\\bm(ana)?g(e)?m(en)?t\\.?\\b)',
                                    '(\\bmanufactur(ers?|ing)\\b)',
                                    '(\\bma(nors?|ssage|rket((er)?s?|ing)?)\\b)',
                                    '(\\bme(chanics?|dical|morials?|t(hodist|ro(politan)?))\\b)',
                                    '(\\bminist(ers?|ry|ries)\\b)',
                                    '(\\bmo(biles?|rtgages?|sque|t(els?|ors?)|ving)\\b)',
                                    '(\\bmu(fflers?|ltiplex(es)?|nicipal(ity)?|s(eums?|ic(ians?)?))\\b)',
                                    '(\\bnat((iona)?l|ions?)\\b)',
                                    '(\\bne(twork(s|ing)?|w)\\b)',
                                    '(\\bno(n(\\-|\\s)?profit|odles?)\\b)',
                                    '(\\bnurs(er(ies|y)|ing)\\b)',
                                    '(\\bo(il|lde?)\\b)',
                                    '(\\boffices?\\b)',
                                    '(\\boptic(al|ians?)\\b)',
                                    '(\\bor(ganizations?|thodo(x|nti(c|st)s?))\\b)',
                                    '(\\bo(utfitter|wner)s?\\b)',
                                    '(\\bpa(cific|int(ers|ings?)?|y\\-?day)\\b)',
                                    '(\\b(p\\.?a\\.?|p\\.?b?\\.?c\\.?)\\b)',
                                    '(\\bpe(ntecostal|r(formance|sonal)s?|sts?)\\b)',
                                    '(\\bpet(roleum|s|smart)?\\b)',
                                    '(\\bp(h(armaceuticals?|otograph(ers?|y))|izzas?)\\b)',
                                    '(\\bp(ar(king|tner(ship)?s?)|l(a(ce|nned)|azas?|c|umb(ers?|ing))|ortfolios?|ub)\\b)',
                                    '(\\bpr(ayers?|e(mier|s(byterian|ervation)|\\-?schools?)|i(me|nt(ing|ers?)|sons?)|o(ductions?|(fessional)?s?|grams?|pert(ies|y)))\\b)',
                                    '(\\bpubli(c(ations?|i(sts?|ty))?|sh(ers?|ing)?)\\b)',
                                    '(\\breal(t(y|ors?)|(\\-|\\s{1})estate)\\b)',
                                    '(\\bre(ality|co(rd(ing|s)?|very)|development|gional|hab(ilitation)?|model(s?|ers?|ing)?|n(ovat(i(ng|ons?)|ors?)|tals?)|pairs?|s(iden(ce|tial)|o(rt|lution|urce)|taurant)s?|tail(ers?)?)\\b)',
                                    '(\\bs(a(il|v)ings?|al(oo?n|ad)s?|c(ientific|hools?)|e(afood|curity|minar(ies|y)|niors?|ptic|rvices?|wing)|ight\\-?seeing|kin|quares?)\\b)',
                                    '(\\bsh(o(es?|wrooms?|p(s|pes?)?)|ipp(ers?|ing))\\b)',
                                    '(\\bso(ciet(ies|y)|ft\\-?ware|lutions?|up)\\b)',
                                    '(\\bsp(a|ecialists?|ort(s|ing|\\-?fishing)?)\\b)',
                                    '(\\bst(a(ff(ing|ers?)?|te|tions?)|orage|udios?|reets?)\\b)',
                                    '(\\bsu(ccessors?|ites?|ppl(ies|y)|r(g(e(ons?|ry)|ical)|plus)|per(\\-?stores?|vis(ing|ors?))|shi|n\\-?(rise|set))\\b)',
                                    '(\\bsy(stems?|nagogue)\\b)',
                                    '(\\bta(bernacle|nning|xis?|x(es)?)\\b)',
                                    '(\\bthe(at(er|re)|rap(eutics?|ists?|y))?\\b)',
                                    '(\\bt(e(ch(nolog(ies|y))?|mples?|r(rac|mit)es?)|i(nting|res?)|o(ur(ing|s)?|ys?|w(ers?|ing)|wn(e|\\-?ho(m|us)es?)?))\\b)',
                                    '(\\btr(a((d|in)ing|ils?|nsportation)|opical|u(ck(ers?|ing)|st(ee)?s?))\\b)',
                                    '(\\bu(n(i(versity|ted)|limited)|rban|tilit(ies|y))\\b)',
                                    '(\\bv(e(hicle|n(d(ing|or)|ture)|ter(an|inar(ian|y)))s?|i(deo|ew|llage|neyard|p)s?)\\b)',
                                    '(\\bwa(rehous(es?|ing)|shing)\\b)',
                                    '(\\bw((elln|irel)ess|i\\-?fi|ine(ry|ies)?|orld|reck(ing|ers?))\\b)',
                                    '(\\by(mca|outh)\\b)',
                                    '(\\b(up|down|mid)\\-?town\\b)',
                                    '(\\d+)|(\\&)|(\\@)|(\\!)|(\\#)|(\\%)|(\\/)', # non-person characters
                                    "(\\'s\\s{1,}|\\'s$|s\\'\\s{1,}|s\\'$)", # possessives
                                    '(https?\\:\\/\\/)|(www\\.)|(\\.(biz|com|edu|gov|int|mil|net|org))', # websites
                                    '(\\b(a(s|t)|by|for|in|o(n|ut)|off?|too?)\\b)', # common prepositions
                                    '(\\b(b(ou)?le?v(ar)?d|r(oa)?d)\\b)', # common street indicators
                                    '(\\b((north|east|south|west)(ern)|north\\-?(east|west)|south\\-?(east|west))\\b)', # cardinal directions
                                    '(^\\S+$)'), # flag if no spaces in name
                                  collapse = '|')
)